version: '3'

services:
  scylla:
    container_name: 'scyllaDB'
    image: 'scylladb/scylla'
    restart: always
    #command: --api-address 0.0.0.0
    networks:
      - custom-bridge
    ports:
      - "0.0.0.0:9042:9042"
      - "0.0.0.0:9160:9160"

  rest_api:
    container_name: 'restapi_service'
    build: ./rest_api/
    ports:
      - "8000:8000"
    volumes:
      - ./rest_api/app:/root/service
    networks:
      - custom-bridge

networks:
  custom-bridge: